name: Upload to PPA

on:
  push:
    branches: [ main ]

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Setup environment
      run: |
        sed -i -e '/^#/d' .github/config.env
        sed -i -e '/^$/d' .github/config.env
        cat .github/config.env >> "${GITHUB_ENV}"
      shell: bash
    - if: env.upload_to_ppa == 1
      name: Import GPG key
      id: gpgkey
      uses: crazy-max/ghaction-import-gpg@v5
      with:
        gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
        passphrase: ${{ secrets.GPG_PASSPHRASE }}
    - if: env.upload_to_ppa == 1
      name: Save GPG info
      run: |
        echo gpg_name=${{ steps.gpgkey.outputs.name }} >> "${GITHUB_ENV}"
        echo gpg_email=${{ steps.gpgkey.outputs.email }} >> "${GITHUB_ENV}"
      shell: bash
    - if: env.upload_to_ppa == 1
      name: Upload source packages to PPA
      run: .github/scripts/ppa.sh
      shell: bash
